import { create } from "zustand";

const useNewTrade = create((set) => ({
  userId: "",
  assetPair: "",
  broker: "",
  direction: "",
  entryPrice: "",
  takeProfit: "",
  stopLoss: "",
  riskPercent: "",
  riskAmount: "",
  lotSize: "",
  tradedPips: "",
  session: "",
  strategyIds: [],
  rr: "",
  pnl: "",
  journal: "",
  status: "",
  createdAt: "",
  closedAt: "",
  attachments: "",
  setuserId: (value) => set(() => ({ userId: value })),
  setassetPair: (value) => set(() => ({ assetPair: value })),
  setbroker: (value) => set(() => ({ broker: value })),
  setdirection: (value) => set(() => ({ direction: value })),
  setentryPrice: (value) => set(() => ({ entryPrice: value })),
  settakeProfit: (value) => set(() => ({ takeProfit: value })),
  setstopLoss: (value) => set(() => ({ stopLoss: value })),
  setriskPercent: (value) => set(() => ({ riskPercent: value })),
  setriskAmount: (value) => set(() => ({ riskAmount: value })),
  setlotSize: (value) => set(() => ({ lotSize: value })),
  settradedPips: (value) => set(() => ({ tradedPips: value })),
  setsession: (value) => set(() => ({ session: value })),
  setstrategyIds: (value) => set(() => ({ strategyIds: value })),
  setrr: (value) => set(() => ({ rr: value })),
  setpnl: (value) => set(() => ({ pnl: value })),
  setjournal: (value) => set(() => ({ journal: value })),
  setstatus: (value) => set(() => ({ status: value })),
  setcreatedAt: (value) => set(() => ({ createdAt: value })),
  setclosedAt: (value) => set(() => ({ closedAt: value })),
  setattachments: (value) => set(() => ({ attachments: value })),
}));

export default useNewTrade;
